volumes:
  bot_log_share: {}
  loki_stora_data: {}

services:
  telegram-bot:
    build:
      context: ./telegram_bot
    env_file:
      - ./telegram_bot/.env
    volumes:
      - bot_log_share:/app/logs

  # http://loki-local:3100
  loki-local:
    image: grafana/loki:2.9.8
    volumes:
      - loki_stora_data:/loki

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"

  promtail:
    image: grafana/promtail:2.9.8
    volumes:
      - bot_log_share:/logs
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
