apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "telegram-bot.fullname" . }}
  labels:
    {{- include "telegram-bot.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
        {{- include "telegram-bot.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
      - port: metrics-port