{{- if not .Values.secret.useExisting }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-class
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secret.arn }}
        objectType: secretsmanager
        jmesPath:
        {{- range .Values.secret.keys }}
          - objectAlias: {{ . }}_alias
            path: {{ . }}
        {{- end }}
    region: {{ .Values.secret.region }}
  secretObjects:
    - data:
    {{- range .Values.secret.keys }}
        - key: {{ . }}
          objectName: {{ . }}_alias
    {{- end }}
      secretName: {{ .Values.secret.extra_name }}
      type: Opaque
{{- end }}