apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-manager.fullname" . }}
  labels:
    {{- include "user-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-manager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: user-manager
          image: "{{ .Values.image_user_manager.repository }}:{{ .Values.image_user_manager.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image_user_manager.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
              name: http-port
          env:
            - name: FLASK_APP
              value: manager.py
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: FLASK_SECRET_KEY
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_DB
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: DB_HOST
