name: User Manager Bot CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'user_manager/**'
      - '.github/workflows/user_manager_k8s.yml'

env:
  PROJECT_NAME: bitrix_24_salesman_gpt
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./user_manager/app

      - name: Analysing the code with pylint
        run: |
          pylint manager.py
        working-directory: ./user_manager/app

  build_and_push:
    outputs:
      new_tag_liquibase: ${{ steps.push_image.outputs.new_tag_liquibase }}
      new_tag_user_manager: ${{ steps.push_image.outputs.new_tag_user_manager }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        working-directory: ./user_manager/
        run: docker build . --file Dockerfile --tag $PROJECT_NAME

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}_user_manager
          CURRENT_BRANCH=${{ github.head_ref || github.ref_name }} 
          if [ "$CURRENT_BRANCH" == "main" ]; then
            TAG=latest
          else
            TAG="$CURRENT_BRANCH"
          fi
          docker tag $PROJECT_NAME $IMAGE_ID:$TAG
          docker push $IMAGE_ID:$TAG
          echo "new_tag_user_manager=$TAG" >> $GITHUB_OUTPUT
        id: push_image
  
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build_and_push
    steps:
      - uses: actions/checkout@v4

      - name: EKS login
        run: |
          aws eks \
          --region ${{ vars.AWS_REGION }} \
          update-kubeconfig \
          --name ${{ vars.EKS_NAME }}

      - uses: azure/setup-helm@v4.2.0

      - name: helm upgrade --install
        run: |
          helm \
          upgrade --install \
          --namespace ${{ vars.KUBE_NS }} \
          user-manager \
          --set image_user_manager.tag=${{ needs.build_and_push.outputs.new_tag_user_manager }} \
          --set ingress.basic_auth=${{ secrets.BASIC_AUTH_CREDS }} \
          --wait \
          ./user-manager
        working-directory: ./charts
